compact.jats.xml:
  decode:
    # At present, only a limited number of `Parameter` props are supported
    strip-props:
      - Parameter.default
      - Parameter.validator
      - Parameter.value

md:
  decode:
    # TODO: Fix various issues, including below props
    skip: true
    strip-props:
      - NumberValidator.exclusive_minimum
      - NumberValidator.exclusive_maximum
