[package]
name = "kernel-micro"
version = "0.0.0"
edition = "2021"

[dependencies]
app = { path = "../app" }
kernel = { path = "../kernel" }
nix = { version = "0.27.1", features = ["signal"] }
which = "6.0.0"
