[package]
name = "model"
version = "0.0.0"
edition = "2021"

[dependencies]
app = { path = "../app" }
common = { path = "../common" }
format = { path = "../format" }
schema = { path = "../schema" }
secrets = { path = "../secrets" }
