compact.jats.xml:
  decode:
    strip-types:
      # TODO: Implement encoding and decoding `IfBlock`
      - IfBlock

myst:
  decode:
    strip-props:
      # MyST does not support lang currently
      - IfBlockClause.programming_language

