# Add plugin name, and the URL to its `stencila-plugin.toml` file, in alphabeical order of name. e.g.
#
#   myplugin = "https://raw.githubusercontent.com/myorg/myplugin/main/stencila-plugin.toml"
#
# The plugin name used here, should be the same as its `stencila-plugin.toml` file.
# If it is not, the plugin will be ignored.
