# Add plugins name and URL to manifest file in alphabeical order of name.
#
# The plugin name used here, should be the same as in the manifest file.
# If it is not the plugin will be ignored.

node-example = "https://raw.githubusercontent.com/stencila/plugin-example-node/main/manifest.toml"
python-example = "https://raw.githubusercontent.com/stencila/plugin-example-python/main/manifest.toml"
