compact.jats.xml:
  decode:
    # TODO: Support encoding to JATS
    skip: true

md:
  decode:
    strip-props:
      # This stripping should be part of the codec/merging
      # back in to prevent overwrite of in-memory properties
      - ModifyInline.content
      - ModifyInline.operations
