[package]
name = "agent"
version = "0.0.0"
edition = "2021"

[dependencies]
app = { path = "../app" }
common = { path = "../common" }
fastembed = "1.10.0"
format = { path = "../format" }
merge = "0.1.0"
schema = { path = "../schema" }
