[package]
name = "server"
version = "2.0.0-beta.1"
authors = ["Nokome Bentley <nokome@stencila.io"]
edition = "2021"

[dependencies]
axum = { version = "0.7.5", features = ["ws"] }
codecs = { path = "../codecs" }
common = { path = "../common" }
document = { path = "../document" }
format = { path = "../format" }
mime_guess = { workspace = true }
node-id = { path = "../node-id" }
rust-embed = { version = "8.5.0", features = ["interpolate-folder-path", "include-exclude"] }
secrets = { path = "../secrets" }
tower-cookies = "0.10.0"
tower-http = { version = "0.5.2", features = ["trace"] }

[dev-dependencies]
common-dev = { path = "../common-dev" }
