compact.jats.xml:
  decode:
    strip-types:
      # TODO: Fix issues with encoding and decoding `CodeExpression`
      - CodeExpression
md:
  encode:
    strip-props:
      # Output properties are not supported in Markdown
      - CodeExpression.output
myst:
  encode:
    strip-props:
      # The following properties are not supported in MyST
      - CodeExpression.programming_language
      - CodeExpression.execution_mode
      - CodeExpression.output
