# TODO: Consider encoding `Delete` and `Insert` to JATS
compact.jats.xml:
  decode:
    skip: true

# TODO: Enable when decoding of `Insert` with more complex
# inlines is implemented
md:
  decode:
    skip: true
