compact.jats.xml:
  decode:
    strip-types:
      - ModifyBlock

smd:
  decode:
    strip-props:
      # This stripping should be part of the codec/merging
      # back in to prevent overwrite of in-memory properties
      - ModifyBlock.content
      - ModifyBlock.operations

myst:
  decode:
    strip-props:
      # As for Markdown
      - ModifyBlock.content
      - ModifyBlock.operations

qmd:
  decode:
    strip-props:
      # As above
      - ModifyBlock.content
      - ModifyBlock.operations

pandoc:
  decode:
    # TODO: remove when implemented
    skip: true
