compact.jats.xml:
  decode:
    strip-types:
      # TODO: implement encoding and decoding for `CallBlock`
      - CallBlock

pandoc:
  decode:
    strip-props:
      # Not currently supported
      - CallArgument.value

