compact.jats.xml:
  decode:
    strip-types:
      # TODO: Implement encoding and decoding `StyledBlock`
      - StyledBlock

smd:
  decode:
    strip-props:
      # Not supported in Markdown
      - StyledBlock.style_language

myst:
  decode:
    strip-props:
      # As for Markdown
      - StyledBlock.style_language
