name: "💡 Feature"
description: Document a new feature
title: "feat(<context>): <title>"
labels:
  - "type: feature"
  - "needs triaging"
projects:
  - stencila/8
assignees:
  - nokome
  - simonwinter
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide an explanation of the feature
      placeholder: Describe your feature request
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Reference Issues"
      description: Link to related issues
      placeholder: "#Issues IDs"
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Implementation PR"
      description: Associated pull request
      placeholder: "#Pull Request ID"
    validations:
      required: false