name: "💡 Feature"
description: Suggest a feature
title: "feat(<context>): <title>"
labels:
  - "type: feature"
projects:
  - stencila/8
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to give us your idea ✨.
  - type: dropdown
    id: product
    attributes:
      label: Which product?
      description: Which Stencila product is this idea for.
      options:
        - Stencila VSCode extension
        - Stencila CLI
        - Other
      default: 0