[package]
name = "codec-markdown"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { path = "../codec" }
codec-json5-trait = { path = "../codec-json5-trait" }
codec-markdown-trait = { path = "../codec-markdown-trait" }
codec-text-trait = { path = "../codec-text-trait" }
markdown = { git = "https://github.com/nokome/markdown-rs", rev = "16ae3ac4f27ec26737db7729ed7c033469f27a2b" }
winnow = "0.6.18"

[dev-dependencies]
common-dev = { path = "../common-dev" }
