compact.jats.xml:
  decode:
    strip-types:
      # TODO: Support decoding math blocks
      - MathBlock
md:
  decode:
    strip-props:
      # TODO: Fix consistency of trimming code
      - MathBlock.code
