[package]
name = "assistant-openai"
version = "0.0.0"
edition = "2021"

[dependencies]
assistant = { path = "../assistant" }
async-openai = "0.20.0"
cached = { version = "0.50.0", features = ["async"] }
