[package]
name = "assistants"
version = "0.0.0"
edition = "2021"

[dependencies]
assistant = { path = "../assistant" }
cli-utils = { path = "../cli-utils" }
common = { path = "../common" }
model = { path = "../model" }
models = { path = "../models" }
plugins = { path = "../plugins" }
