[package]
name = "lsp"
version = "0.0.0"
edition = "2021"

[dependencies]
assistants = { path = "../assistants" }
async-lsp = { version = "0.2.0", features = ["tokio"] }
codecs = { path = "../codecs" }
codec-text-trait = { path = "../codec-text-trait" }
common = { path = "../common" }
document = { path = "../document" }
node-execute = { path = "../node-execute" }
schema = { path = "../schema" }
tokio-util = { version = "0.7.10", features = ["compat"] }
tower = "0.4.13"
tracing-subscriber = "0.3.18"
