[package]
name = "lsp"
version = "0.0.0"
edition = "2021"

[dependencies]
async-lsp = { version = "0.2.0", features = ["tokio"] }
codecs = { path = "../codecs" }
common = { path = "../common" }
document = { path = "../document" }
tokio-util = { version = "0.7.10", features = ["compat"] }
tower = "0.4.13"
tracing-subscriber = "0.3.18"
