compact.jats.xml:
  decode:
    # At present, only a limited number of `Parameter` props are supported
    strip-props:
      - Parameter.value
      - ParameterOptions.default
      - ParameterOptions.validator

smd:
  decode:
    # Encoding/decoding of parameter to Markdown is not supported (source property)
    strip-props:
      - Parameter.value

myst:
  decode:
    # As for Markdown
    strip-props:
      - Parameter.value
