compact.jats.xml:
  decode:
    # At present, only a limited number of `Parameter` props are supported
    strip-props:
      - Parameter.value
      - ParameterOptions.default
      - ParameterOptions.validator

md:
  decode:
    # Encoding/decoding of parameter to Markdown is not supported (source property)
    strip-props:
      - Parameter.value
