compact.jats.xml:
  decode:
    # At present, only a limited number of `Parameter` props are supported
    strip-props:
      - Parameter.value
      - ParameterOptions.default
      - ParameterOptions.validator
