[package]
name = "kernel-quickjs"
version = "0.0.0"
edition = "2021"

[dependencies]
codec-markdown-trait = {path = "../codec-markdown-trait" }
kernel = { path = "../kernel" }
rquickjs = { version = "0.6.2", features = ["classes", "futures", "macro", "parallel"] }

[dev-dependencies]
common-dev = { path = "../common-dev" }
test-log = { version = "0.2.15", default-features = false, features = ["trace"] }
