compact.jats.xml:
  decode:
    strip-types:
      # TODO: Implement encoding and decoding `IncludeBlock`
      - IncludeBlock

pandoc:
  encode:
    # TODO: Remove when implemented
    strip-types:
      - IncludeBlock
