dom.html:
  encode:
    # TODO: Fix issue when indenting HTML
    skip: true

compact.jats.xml:
  canonical: true

jats.xml:
  decode:
    # TODO: Enable when Cite nodes are supported
    skip: true

smd:
  decode:
    # TODO: Enable when Cite nodes are supported
    skip: true

myst:
  decode:
    # TODO: As for Markdown
    skip: true
