# TODO: Support the following codec/node type combinations

compact.jats.xml:
  encode:
    strip-types:
      - Delete
      - Insert
  decode:
    strip-types:
      - Call
      - Claim
      - CodeBlock
      - CodeChunk
      - Figure
      - For
      - If
      - Include
      - List
      - MathBlock
      - StyledBlock
      - Table
md:
  encode:
    strip-types:
      - Figure
