# TODO: Support the following codec/node type combinations

compact.jats.xml:
  encode:
    strip-types:
      - DeleteBlock
      - DeleteInline
      - InsertBlock
      - InsertInline
  decode:
    strip-types:
      - CallBlock
      - Claim
      - CodeBlock
      - CodeChunk
      - Figure
      - ForBlock
      - IfBlock
      - IncludeBlock
      - List
      - MathBlock
      - StyledBlock
      - Table
md:
  encode:
    strip-types:
      - Figure
