[package]
name = "agents"
version = "0.0.0"
edition = "2021"

[dependencies]
agent = { path = "../agent" }
agent-ollama = { path = "../agent-ollama" }
agent-openai = { path = "../agent-openai" }
cached = { version = "0.46.1", features = ["async"] }
