[package]
name = "agents"
version = "0.0.0"
edition = "2021"

[dependencies]
agent = { path = "../agent" }
agents-ollama = { path = "../agents-ollama" }
agents-openai = { path = "../agents-openai" }
cached = { version = "0.46.1", features = ["async"] }
