[package]
name = "agents"
version = "0.0.0"
edition = "2021"

[dependencies]
agent = { path = "../agent" }
agent-custom = { path = "../agent-custom" }
agent-ollama = { path = "../agent-ollama" }
agent-openai = { path = "../agent-openai" }
cached = { version = "0.46.1", features = ["async"] }
sea-orm = { version = "0.12.10",  default-features = false, features = ["macros", "sqlx", "sqlx-sqlite", "runtime-tokio-rustls", "with-json", "with-chrono"] }
