compact.jats.xml:
  decode:
    strip-types:
      # TODO: implement decoding `List`
      - List
    strip-props:
      # Decoding of authors not supported, but in fixture
      - authors

# TODO: Fix issues decoding AuthorRole with JSON-LD (?)
compact.jsonld:
  decode:
    skip: true
jsonld:
  decode:
    skip: true

smd:
  decode:
    strip-props:
      # As above
      - authors

myst:
  decode:
    strip-props:
      # As above
      - authors

qmd:
  decode:
    strip-props:
      # As above
      - authors
