[package]
name = "codec-dom"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { path = "../codec" }
codec-dom-trait = { path = "../codec-dom-trait" }
codec-text-trait = { path = "../codec-text-trait" }
quick-xml = { workspace = true }
